server:
  port: 8084
  shutdown: graceful

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2.0
        default-requeue-rejected: false # Send to DLQ instead of infinite loop
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: dummy_user
    password: dummy_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  tracing:
    sampling:
      probability: 1.0 # 100% sampling for development
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans" # Points to the Docker container
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    tags:
      application: ${spring.application.name}
