server:
  port: 8085
  shutdown: graceful

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/commerce_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2.0
        default-requeue-rejected: false # Send to DLQ instead of infinite loop

management:
  tracing:
    sampling:
      probability: 1.0 # 100% sampling for development
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans" # Points to the Docker container
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

payment:
  simulate-success: ${PAYMENT_SIMULATE_SUCCESS:true}
